spellername = "Makur치p"
spellerversion = "0.1.0"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Makur치p spellchecker"
mpu = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Makur치p, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
mpu = "TRANSLATE: A spellchecker for Makur치p, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.mpu"

[windows]
system_product_code = "{REPLACE_WITH_REAL_SYSTEM_PROD_CODE}_is1"
