template = "https://github.com/giellalt/template-lang-und"
rev_id = 241
template_sha = "ccbeecccf23fdaeb9ccde30dcee029b965dd83b6"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-mpu"
__UND2C__ = "mpu"
__UNDEFINED__ = "Makur√°p"
__UND__ = "mpu"
