template = "https://github.com/giellalt/template-lang-und"
rev_id = 230
template_sha = "f93135dcd0289587f23ccda4a615f9d6f4abe835"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-mpu"
__UND2C__ = "mpu"
__UNDEFINED__ = "Makur√°p"
__UND__ = "mpu"
