template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "maku1278"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-mpu"
__UND2C__ = "mpu"
__UNDEFINED__ = "Makur√°p"
__UND__ = "mpu"
