template = "https://github.com/giellalt/template-lang-und"
rev_id = 207
template_sha = "a269a36425ae5380672ca9a7d500980d4f6e7405"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-mpu"
__UND2C__ = "mpu"
__UNDEFINED__ = "Makur√°p"
__UND__ = "mpu"
