template = "https://github.com/giellalt/template-lang-und"
rev_id = 246
template_sha = "b7ba420a949cf8ed3ed70f3b25c8a69c42d2e07f"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-mpu"
__UND2C__ = "mpu"
__UNDEFINED__ = "Makur√°p"
__UND__ = "mpu"
