template = ""
rev_id = 203
template_sha = "5d894079cc37eb932c8a8a50c3f883ff1ca9b92c"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-mpu"
__UND2C__ = "mpu"
__UNDEFINED__ = "Makur√°p"
__UND__ = "mpu"
